# This file was generated by GoReleaser. DO NOT EDIT.
class EcsStabilizer < Formula
  desc "ecs-stabilizer allows you to check to makre sure services are stable"
  homepage "https://github.com/ministryofjustice/opg-ecs-helper"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ministryofjustice/opg-ecs-helper/releases/download/v0.1.1/opg-ecs-helper_0.1.1_Darwin_x86_64.tar.gz"
    sha256 "dd500db0c69643a8bf0102bb05384f5f6268d1c2c9040b474c61225b3f0a3d97"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/ministryofjustice/opg-ecs-helper/releases/download/v0.1.1/opg-ecs-helper_0.1.1_Linux_x86_64.tar.gz"
      sha256 "013dca929f9d0650683eab2a364f66c979aec3c3b45ad17a1d3ccbfb99c1d0ce"
    end
  end

  def install
    bin.install "ecs-stabilizer"
  end
end
