# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EcsRunner < Formula
  desc "ecs-runner allows you to run ECS tasks"
  homepage "https://github.com/ministryofjustice/opg-ecs-helper"
  version "0.5.0-beta.4"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ministryofjustice/opg-ecs-helper/releases/download/v0.5.0-beta.4/opg-ecs-helper_Darwin_x86_64.tar.gz"
      sha256 "e65c9363714a4a2b1016cdcf0c5d4a4219d05b3c1217df9b148dacd96e8fea30"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ministryofjustice/opg-ecs-helper/releases/download/v0.5.0-beta.4/opg-ecs-helper_Linux_x86_64.tar.gz"
      sha256 "abe38fe2e2b9d36f681c7e48b3012d57525c19014ad34908b01da4d3387050e2"
    end
  end

  def install
    bin.install "ecs-runner"
  end
end
