# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EcsRunner < Formula
  desc "ecs-runner allows you to run ECS tasks"
  homepage "https://github.com/ministryofjustice/opg-ecs-helper"
  version "0.5.0-SP-1219.9"

  on_macos do
    url "https://github.com/ministryofjustice/opg-ecs-helper/releases/download/v0.5.0-SP-1219.9/opg-ecs-helper_Darwin_x86_64.tar.gz"
    sha256 "60bb71d5f0d7fda741967612c0792682b33a262a914bf4dd4e9753babf26ff9b"

    def install
      bin.install "ecs-runner"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the EcsRunner
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ministryofjustice/opg-ecs-helper/releases/download/v0.5.0-SP-1219.9/opg-ecs-helper_Linux_x86_64.tar.gz"
      sha256 "dbb4536f845e8733d7d49aed072bb678331fbb88ff47368c6e9437450fe4b8af"

      def install
        bin.install "ecs-runner"
      end
    end
  end
end
