# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SiriusFailover < Formula
  desc "sirius-failover allows you to failover Sirius"
  homepage "https://github.com/ministryofjustice/opg-sirius-failover"
  version "1.1.0-beta.3"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ministryofjustice/opg-sirius-failover/releases/download/v1.1.0-beta.3/opg-sirius-failover_Darwin_x86_64.tar.gz"
      sha256 "bbc335c03bc29dd5282580f7a4cc51058fb861fd0582b4152129259f93bd3408"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ministryofjustice/opg-sirius-failover/releases/download/v1.1.0-beta.3/opg-sirius-failover_Linux_x86_64.tar.gz"
      sha256 "bf82d9a4dd65124d53db7ac8ae0cedc352917d1a727b6d43defb02f69f31a2e0"
    end
  end

  def install
    bin.install "sirius-failover"
  end
end
