# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SiriusFailover < Formula
  desc "sirius-failover allows you to failover Sirius"
  homepage "https://github.com/ministryofjustice/opg-sirius-failover"
  version "1.0.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/ministryofjustice/opg-sirius-failover/releases/download/v1.0.0/opg-sirius-failover_Darwin_x86_64.tar.gz"
    sha256 "0406abbf79cb6b334653bfaafca91b980e416321905b850e8b8c9469019f7667"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/ministryofjustice/opg-sirius-failover/releases/download/v1.0.0/opg-sirius-failover_Linux_x86_64.tar.gz"
    sha256 "ed066b86c39d6ab6d6999612c72904fdd3f33dd22b1e6c9a9e2ba19706c8342d"
  end

  def install
    bin.install "sirius-failover"
  end
end
