# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SiriusFailover < Formula
  desc "sirius-failover allows you to failover Sirius"
  homepage "https://github.com/ministryofjustice/opg-sirius-failover"
  version "1.1.0-beta.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/ministryofjustice/opg-sirius-failover/releases/download/v1.1.0-beta.1/opg-sirius-failover_Darwin_x86_64.tar.gz"
    sha256 "38292d374502a86785bbfdbd27c8973c4fcd3ad1724533cdd72df1ec7920dc17"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/ministryofjustice/opg-sirius-failover/releases/download/v1.1.0-beta.1/opg-sirius-failover_Linux_x86_64.tar.gz"
    sha256 "69dba19d9ea55547991c5cdf0c7c39c03cf2b8fd627d1ee4b1558819e973e056"
  end

  def install
    bin.install "sirius-failover"
  end
end
